// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  datasource: {
    // Use the direct (non-pooled) URL for migrations so Prisma can run DDL
    // statements that are incompatible with PgBouncer/Neon's pooled endpoint.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
